# Generated by Django 3.2 on 2023-01-25 05:46

import django.contrib.auth.validators
import users.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validator.username_value_not_me], verbose_name='Ник пользователя'),
        ),
    ]
