# Generated by Django 3.2 on 2023-01-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_unique_username_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
    ]
