# Generated by Django 3.2 on 2023-01-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_unique_email_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_username',
        ),
    ]
