# Generated by Django 3.2 on 2023-01-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
