# Generated by Django 3.2 on 2023-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(help_text='Жанр, к которой будет относиться тайтл', through='reviews.GenreTitle', to='reviews.Genres', verbose_name='Жанр'),
        ),
    ]
