# Generated by Django 3.2 on 2023-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_titles_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, through='reviews.GenreTitle', to='reviews.Genres'),
        ),
    ]
