# Generated by Django 3.2 on 2023-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_titles_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(through='reviews.GenreTitle', to='reviews.Genres'),
        ),
    ]
